[package]
name = "srt-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
nova = "0.5.4"
zimu-ast = { path = "../zimu-ast" }